mysite/awesome/urls.py
from django.urls import path
from . import views


app_name = 'awesome'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:case_id>/', views.detail, name='detail'),
    path('test_pt/', views.pt, name='pt'),
    path('node/', views.node, name='node'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('awesome/', include('awesome.urls'))
]

mysite/awesome/models.py
from django.db import models


class Cases(models.Model):
    objects = models.Manager()

    id = models.AutoField(primary_key=True)
    case_name = models.CharField(max_length=50)
    method = models.CharField(max_length=10)
    url_path = models.CharField(max_length=200)
    data = models.TextField(null=True)
    expected = models.TextField(null=True)
    create_time = models.DateTimeField(auto_now_add=True, auto_created=True)
    modify_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.case_name

mysite/awesome/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django import forms
import json

from .models import Cases


def index(request):
    case_list = Cases.objects.all()
    context = {
        'case_list': case_list
    }
    return render(request, 'awesome/index.html', context)


def detail(request, case_id):
    case = get_object_or_404(Cases, id=case_id)
    return render(request, 'awesome/detail.html', context={'case': case})


class PtForm(forms.Form):
    case_name = forms.CharField(label='用例名称', min_length=2, max_length=10)
    method = forms.CharField(label='请求方法', max_length=6)


def pt(request):
    if request.method == 'POST':
        form = PtForm(request.POST)
        print(request.POST['case_name'])
        if form.is_valid():
            return HttpResponse('请求成功')
    else:
        form = PtForm()
    return render(request, 'awesome/pt.html', locals())


@require_http_methods(['GET'])
def node(request):
    resp = {}
    try:
        resp['cases'] = json.loads(serializers.serialize('json', Cases.objects.filter(method='get')))
        resp['status_code'] = 0
    except Exception as e:
        resp['error_msg'] = e
        resp['status_code'] = 1
    return JsonResponse(resp)

mysite/awesome/templates/awesome/detail.html
<h1>{{case.method}}</h1>
<li>
    name: {{case.case_name}}
</li>
<li>
    method:{{case.method}}
</li>
{% if data %}
<li>
    data:{{case.data}}
</li>
{% else %}
<li>
    data:null
</li>
{% endif %}

mysite/awesome/templates/awesome/index.html
{% if case_list %}
    <ul>
        {% for case in case_list %}
        <li><a href="{% url 'awesome:detail' case.id %}">{{case.case_name}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No cases are available</p>
{% endif %}

mysite/awesome/templates/awesome/pt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test_pt</title>
</head>
<body>
<form action="/awesome/test_pt/" method="post">
    {% csrf_token %}
    <div class="headers">
        {{form}}
    </div>
    <input type="submit" value="请求">
</form>


</body>
</html>